package helpers;
public enum Icons {
    HOUSE, MAGINFYING_GLASS, USER, FACEBOOK, CHECK, DOWNLOAD, TWITTER, IMAGE, INSTAGRAM, PHONE, TIKTOK,
    BARS, ENVELOPE, LINKEDIN, STAR, BLOCATION_DOT, GITHUB, MUSIC, WAND_MAGIC_SPARKLESS, HEART, ARROW_RIGHT,
    DISCORD, CICLE_XMARK, BOMB, POO, CAMERA_RETRO, XMARK, YOUTUBE, CLOUD, COMMENT, CARET_UP, TRUCK_FAST, WORDPRESS, PEN_NIB,
    ARROW_UP, HIPPO, FACE_SMILE, CALENDAR_DAYS, PAPERCLIP, SLACK, SHIED_HAVLED, FIGMA, FILE, BELL, CART_SHOPPING, CLIPBOARD,
    FILTER, CIRCLE_INFO, ARROW_UP_FROM_BRACKET, ALARM_CLOCK, BOLT, RAYGUN, CAR, GHOST, APPLE, MUG_HOT, CIRCLE_USER, PEN,
    GOOGLE, UMBRELLA, GIFT, FILM, STRIPE, LIST, GEAR, ALGOLIA, TRASH, CIRCLE_UP, DOCKER, CIRCLE_DOWN, INBOX, ROTATE_RIGHT,
    LOCK, WINDOWS, HEADPHONES, VOLUME, BARCODE, TAG, BOOK, BOOKMARK, PAYPAL, CAMERA, STACK_OVERFLOW, FONT, VIDEO, CIRCLE_HALF_STROKE,
    DROPLET, PEN_TO_SQUARE, SHARE_FROM_SQUARE, PLUS, MINUS, KICKSTARTER, SHARE, CIRCLE_EXCLAMATION, FIRE, EYE, EYE_SLASH, DRIBBLE,
    PLANT, MAGNET, HAND, FOLDER, FLODER_OPEN, MONEY_BILL, DROPBOX, THUMBS_UP, THUMBS_DOWN, COMMENTS, LEMON, KEY, THUMBTACK,
    GEARS, PAPER_PLANE, CODE, SQUARESSPACE, GLOBE, TRUCK, CITY, TICKET, TREE, WIFI, PAINT_ROLLER, BICYCLE, ANDROID, 
    SLIDERS, BRUSH, HASTAG, FLASH, BRIEFCASE, COMPASS, DUMPSTER_FIRE, PERSON, PERSON_DRESS, SHOPIFY, ADDRESS_BOOK, BATH,
    HANDSHAKE, MEDIUM, SNOWFLAKE, RIGHT_TO_BRACKET
}
